<a href="https://colab.research.google.com/github/Amani-K-code/Data-Wrangling/blob/main/Airplane_Crashes_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1
Downloading and loading dataset (Airplane_crashes_dataset)

In [11]:
import pandas as pd
import kagglehub
import os

# Method 1: Manual Download and Upload of the dataset
# df_air = pd.read_csv("https://github.com/Amani-K-code/Data-Wrangling/blob/main/Airplane_Crashes_and_Fatalities_Since_1908.csv")

# Method 2: Downloading the dataset directly from Kaggle into Colab
path = kagglehub.dataset_download("saurograndi/airplane-crashes-since-1908")
print("The path to the dataset file: ", path)

csv_file = [f for f in os.listdir(path) if f.endswith('.csv')][0]
df_air = pd.read_csv(os.path.join(path, csv_file))

Using Colab cache for faster access to the 'airplane-crashes-since-1908' dataset.
The path to the dataset file:  /kaggle/input/airplane-crashes-since-1908

# Question 2
Number of rows and Columns

In [12]:
df_air.shape

(5268, 13)

# Question 3
Last 75 rows in the dataset

In [13]:
df_air.tail(75)

,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
5193,03/15/2008,08:15,"Nbagu, Nigeria",Trade Wings Aviation Ltd.,NaN,Lagos - Bebi Air Strip,Beechcraft 1900D,5N-JAH,UE-322,3.0,3.0,0.0,The plane crashed while en route. Wreckage was...
5194,04/03/2008,11:00,"Lawa, Suriname",Blue Wing Airlines,NaN,Paramaribo - Lawa,Antonov An-28,PZ-TSO,1AJ007-17,19.0,19.0,0.0,While attempting to land the crew aborted the ...
5195,04/09/2008,23:27,"Bundeena, Australia",Avtex Air Services,NaN,Sydney - Brisbane,Swearingen SA227AC Metroliner III,VH-OZA,AC-600,1.0,1.0,0.0,The pilot of the mail plane reported some mino...
5196,04/11/2008,22:15,"Chrisinau, Moldova",Kata Transportation,NaN,"Chrisinau, Moldova - Antalya, Turkey - Sudan",Antonov An-32,ST-AZL,3009,8.0,8.0,0.0,Just minutes after the take off the plane trie...
5197,04/15/2008,14:30,"Goma, Congo",Hewa Bora Airways,NaN,Goma - Kisangani - Kinshasa,McDonnell Douglas DC-9-51,9Q-CHN,47731,85.0,0.0,47.0,"While attempting to takeoff, the plane failed ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5263,05/20/2009,06:30,"Near Madiun, Indonesia",Military - Indonesian Air Force,NaN,Jakarta - Maduin,Lockheed C-130 Hercules,A-1325,1982,112.0,98.0,2.0,"While on approach, the military transport cras..."
5264,05/26/2009,NaN,"Near Isiro, DemocratiRepubliCongo",Service Air,NaN,Goma - Isiro,Antonov An-26,9Q-CSA,5005,4.0,4.0,NaN,The cargo plane crashed while on approach to I...
5265,06/01/2009,00:15,"AtlantiOcean, 570 miles northeast of Natal, Br...",Air France,447,Rio de Janeiro - Paris,Airbus A330-203,F-GZCP,660,228.0,228.0,0.0,The Airbus went missing over the AtlantiOcean ...
5266,06/07/2009,08:30,"Near Port Hope Simpson, Newfoundland, Canada",Strait Air,NaN,Lourdes de BlanSablon - Port Hope Simpson,Britten-Norman BN-2A-27 Islander,C-FJJR,424,1.0,1.0,0.0,The air ambulance crashed into hills while att...
5267,06/08/2009,NaN,"State of Arunachal Pradesh, India",Military - Indian Air Force,NaN,Mechuka for Jorhat,Antonov An-32,NaN,NaN,13.0,13.0,0.0,The military transport went missing while en r...

# Question 4:
## Missing data

In [14]:
# Checking to see whether it is correct that all the columns except the first have missing values as the question suggests.
df_air.isna().any()

Date            False
Time             True
Location         True
Operator         True
Flight #         True
Route            True
Type             True
Registration     True
cn/In            True
Aboard           True
Fatalities       True
Ground           True
Summary          True
dtype: bool

In [15]:
df_air.isnull().sum()

Date               0
Time            2219
Location          20
Operator          18
Flight #        4199
Route           1707
Type              27
Registration     335
cn/In           1228
Aboard            22
Fatalities        12
Ground            22
Summary          390
dtype: int64

## Handling Missing Data
Please refer to the above statistics for the reasons to the method choices

In [16]:
df_air["Time"] = df_air["Time"].fillna("Unknown")                       # TIME - 2219 :- Fill the cells with the 'Unknown' place holder since it is a text field

df_air = df_air.dropna(subset = ["Location"])                           # LOCATION - 20:- since they are a few data cells dropping the rows looses minimal data compared to the dataset size.

df_air["Operator"] = df_air["Operator"].fillna("Unknown")               # OPERATOR - 18:- since they are a few data cells with missing values we replaced the missing data with the place holder 'Unknown' since its text

df_air = df_air.drop(columns=["Flight #"])                              # FLIGHT# - 4199:- since the number of data cells with missing data is very close to the dataset size then we decided to drop the whole column since it hardly carries any usable information.

df_air["Route"] = df_air["Route"].fillna("Unknown")                     # ROUTE - 1707:- since the route is specific text and cannot be made up or given a value '0' we used an "Unknown" place holder

df_air["Type"] = df_air["Type"].fillna("Unknown")                       # TYPE - 27:- since the type of the aircraft is unknown we saw it fit to just fill the missing data with unknown placeholders

df_air["Registration"] = df_air["Registration"].fillna("Unknown")       # REGISTRATION - 335:- since this is a unique identifier of the place then the number cannot be made up or assumed, therefore we also put an Unknown placeholder for this.

df_air["cn/In"] = df_air["cn/In"].fillna("Unknown")                     # cn/In - 1228:- this is also a unique identifier and hence is also given an "Unknown" placeholder

df_air["Aboard"] = df_air["Aboard"].fillna(df_air['Aboard'].median())   # ABOARD - 22:- since the number of missing data cells are few , we decided to get the median of most of the planes number of passengers aboard and use that median as a placeholder (Large passenger planes skew the average)

df_air = df_air.dropna(subset = ["Fatalities"])                         # FATALITIES - 12:- since it is a very small amount of data cells with missing data we drop the few

df_air["Ground"] = df_air["Ground"].fillna(0)                           # GROUND - 22:- Most crashes have zzero ground fatailities, therefore we fill the missing data cells with '0'

df_air["Summary"] = df_air["Summary"].fillna("No available Summary")    # SUMMARY - 390:- Since this is a free text decription we put a "No available summary" placeholder